### ISSUE TITLE
Lis of components

### ISSUE THREAD

**Issue by Denguss75** [robinolejnik/arduino_mini_can_bus#3]
Hi! I would like to try this but I’m a noob on electronics.... Could you tell me the list of components I will need? I mean what resistors value do I need? What is U3? U2 I guess it’s mcp2515...
Thanks!

**Comment by robinolejnik** [comment]
Hi, U2 is MCP2515, for U3 you can use multiple CAN transceivers, MCP2551 for example.
R1 is just a pull up, 10k should work, R3 is 120 Ohms for termination. R2 is used for slope control, choose a value according your needs. Take a look at the datasheet of your transceiver for reference. In an old project I used 10k, worked fine for me.

Be careful with the schematic and pcb design. I've actually never build and tested the board.
